version: "3.8"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es_container
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
    networks:
      - custom_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 3s
      retries: 10

  api:
    build: .
    container_name: fastapi_container
    depends_on:
      es:
        condition: service_healthy
    environment:
      ES_HOST: "http://es:9200"
    ports:
      - "9567:9567"
    networks:
      - custom_net

networks:
  custom_net:
    driver: bridge